//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flux.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flux.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Length: 8
        ///Content-Type: text/html
        ///Proxy-Connection: Keep-Alive
        ///Connection: Keep-Alive
        ///Transfer-Encoding: chunked
        ///Via: 1.1 TK5-PRXY-21
        ///Expires: Thu, 19 Nov 1981 08:52:00 GMT
        ///Date: Mon, 16 Jan 2012 23:39:47 GMT
        ///Content-Type: text/html; charset=UTF-8
        ///Server: nginx/0.6.30
        ///X-Powered-By: PHP/5.2.4-2ubuntu5.6
        ///Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
        ///Pragma: no-cache
        ///X-Pingback: http://whereslou.com/xmlrpc.php
        ///Host: whereslou.com
        ///User-Agent: Mozilla/5.0 (W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HeaderSample {
            get {
                return ResourceManager.GetString("HeaderSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET /foo/bar HTTP/1.1
        ///Content-Length: 8
        ///Content-Type: text/html
        ///Proxy-Connection: Keep-Alive
        ///Connection: Keep-Alive
        ///Transfer-Encoding: chunked
        ///Via: 1.1 TK5-PRXY-21
        ///Expires: Thu, 19 Nov 1981 08:52:00 GMT
        ///Date: Mon, 16 Jan 2012 23:39:47 GMT
        ///Content-Type: text/html; charset=UTF-8
        ///Server: nginx/0.6.30
        ///X-Powered-By: PHP/5.2.4-2ubuntu5.6
        ///Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
        ///Pragma: no-cache
        ///X-Pingback: http://whereslou.com/xmlrpc.php
        ///Host: whereslou.com
        ///Use [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequestSample {
            get {
                return ResourceManager.GetString("RequestSample", resourceCulture);
            }
        }
    }
}
